### ISSUE TITLE
Publish version 1.3.0 to https://pypi.python.org

### ISSUE THREAD

**Issue by telechong** [jamesbowman/openexrpython#12]
Hi James,

The version on pypi is quite old (1.2.0), could you publish the current version 1.3.0 to Pypi, so that the user can install it in a easier way :-) ?

**Comment by jamesbowman** [comment]
Yes, thanks for the reminder. Is done:

https://pypi.python.org/pypi/OpenEXR/1.3.0

Closing.

**Comment by Amir-Arsalan** [comment]
@jamesbowman It looks like there has been some [new updates](https://github.com/openexr/openexr/commits/master) to OpenEXR. I wonder, would it be possible to update the pypi package?
