### ISSUE TITLE
Segmentation fault if line order is set to DECREASING_Y

### ISSUE THREAD

**Issue by tiagoshibata** [jamesbowman/openexrpython#13]
Writing to an output EXR file segfaults if the file is set to DECREASING_Y line order (e.g. the file `ScanLines/Blobbies.exr` in the official [openexr-images repository](https://github.com/openexr/openexr-images)).

Repro: This program copies the header from the `ScanLines/Blobbies.exr` image to an output image and segfaults in the last line:

```python
import OpenEXR

filename = './tests/openexr-images/ScanLines/Blobbies.exr'
assert OpenEXR.isOpenExrFile(filename)
input_file = OpenEXR.InputFile(filename)
assert input_file.isComplete()
output_header = input_file.header()
print(output_header)
output_file = OpenEXR.OutputFile('output.exr', output_header)
channel_data = {
    'R': input_file.channel('R')
}
output_file.writePixels(channel_data)
```

There's no way to use decreasing Y line order currently. The `writePixels` call doesn't crash if increasing Y is explicitly set.

Let me know if someone starts looking into this issue; if not, I will debug it and provide a PR (might take a few weeks though, I'm busy now).

**Comment by tiagoshibata** [comment]
I started taking a look at this yesterday and have a fix ready. I'll do some more testing and see if I find other crashes before opening a PR.

**Comment by jamesbowman** [comment]
Sounds good, thanks.
