### ISSUE TITLE
error reading OpenExrId /Deep from Guerilla render

### ISSUE THREAD

**Issue by TanJeremy** [jamesbowman/openexrpython#14]
Infos = exr.InputFile(path)
IOError: Cannot read image file "/homes/jtan/Documents/test_Deep.exr". The file format version number's flag field contains unrecognized flags.

is ther a possibility to at least be able to check if these file are corrupt or not ? 

[ExrId_Deep_File.zip](https://github.com/jamesbowman/openexrpython/files/1430536/ExrId_Deep_File.zip)

**Comment by tiagoshibata** [comment]
Your application is outputting files with long channel names. Old versions of libIlmImf (< 2.0) don't support it (it was a breaking change from a later revision of the file format, the old format only supports up to 32 characters) and output this generic error message.

It should work if you only use short channel names. Fixing it in the Python bindings would require an update of libIlmImf, which might take some developer time. I might take a look at it in the future, it's also affecting myself ([right now I'm ignoring this error on tests that depend on openexrpython](https://github.com/tiagoshibata/exrsplit/blob/eeee2705db2cce73ed1de16008f5d5c5ef707754/tests/test_openexr_images.py#L34)).

**Comment by TanJeremy** [comment]
ok, no probleme, thx for the reply

**Comment by tiagoshibata** [comment]
@TanJeremy and anyone else with this issue: turns out things just work as expected if you use a newer version of `libIlmImf`. Just recompile `openexrpython` linking to a recent version, no source code changes needed 😄

**Comment by TanJeremy** [comment]
thx tiagoshibata
