### ISSUE TITLE
'Segmentation fault: 11' when trying to embed 'framesPerSecond' variable to exr

### ISSUE THREAD

**Issue by olliers89** [jamesbowman/openexrpython#17]
Hey James,

Working on a mac 10.10.5 with OpenEXR 1.3.0 bindings.

I'm trying to create an exr from a dpx file; can get all the header fields and image data required into the exr, expect for the fps.

I've tried using the 'Imath.Rational(24, 1)' class but it fails with the above error each time I try to commit to a file with OpenEXR.OutputFIle().

Anything I could be doing wrong?

Many thanks,

Luke

**Comment by jamesbowman** [comment]
Aha, OK.

There's no coverage for Imath.Rational() in the test case. Adding it shows that it segfaults in Python 3. 

Committed fix -- are you able to confirm it?

**Comment by olliers89** [comment]
Confirmed!

Thank you kindly.

**Comment by jamesbowman** [comment]
Version 1.3.1 uploaded to PyPI. Closing.
