### ISSUE TITLE
OpenEXR installation error

### ISSUE THREAD

**Issue by jongheeback** [jamesbowman/openexrpython#31]
Hi,
Currently, I am trying to install openEXR 1.3.0 using 'sudo pip3 install openEXR==1.3.0'.
However, error occurs as below.
I am working in Ubuntu 16.04 and using Python 3.5.

Please check and let me know some solutions.

![error_screenshot](https://user-images.githubusercontent.com/36532746/61050156-429d6c80-a421-11e9-885c-24f979d0fa23.png)

**Comment by jamesbowman** [comment]
Try this:

    sudo apt-get install libz-dev

**Comment by jongheeback** [comment]
I fixed it. Thanks for your reply :)
