### ISSUE TITLE
Loading EXR by tiles?

### ISSUE THREAD

**Issue by ShnitzelKiller** [jamesbowman/openexrpython#33]
Is it currently possible to use this interface library to do something like the following?
```python
file.readTiles (startXTiles, endXTiles, startYTiles, endYTiles)
```

One of the benefits of OpenEXR is allowing random access of images without decompressing the entire file. However, as far as I can tell this library doesn't support that type of loading?

**Comment by ShnitzelKiller** [comment]
I've implemented it myself, with a pending pull request. The proposed change is to have a TiledInputFile object which has similar methods to the InputFile, however its `channel` and `channels` methods take min and max X and Y tile indices, allowing to load a crop of a tiled image. The class also has methods `numXTiles()` and `numYTiles()` from the C++ library.

**Comment by jamesbowman** [comment]
Wow. Thanks very much.
