### ISSUE TITLE
When convert exr image to jpg and png, it looks darker than actual. 

### ISSUE THREAD

**Issue by humayun** [jamesbowman/openexrpython#37]
Hi,

I write script to convert exr image into png or jpg, but convert images looks darker. I think it is not rightly converted from float 32 to uint8 or due to alpha channel. 
Here is code: 

```
def convert_exr2png(exr_file, png_file):
    # exr_file = '/data/humayun/test/m_3_3_0_0_0_0.0.exr'
    file = OpenEXR.InputFile(exr_file)
    pt = Imath.PixelType(Imath.PixelType.FLOAT)
    dw = file.header()['dataWindow']
    size = (dw.max.x - dw.min.x + 1, dw.max.y - dw.min.y + 1)

    rgbf = [Image.frombytes("F", size, file.channel(c, pt)) for c in "RGB"]

    extrema = [im.getextrema() for im in rgbf]
    darkest = min([lo for (lo, hi) in extrema])
    lighest = max([hi for (lo, hi) in extrema])
    scale = 255 / (lighest - darkest)

    def normalize_0_255(v):
        return (v * scale) + darkest

    rgb8 = [im.point(normalize_0_255).convert("L") for im in rgbf]
    Image.merge("RGB", rgb8).save(png_file)
```

Here is real image
![m_3_3_0_0_0_0_3](https://user-images.githubusercontent.com/742339/68154242-f3150c00-fefb-11e9-96f0-5940c4afb228.png)
 and converted image 
![m_3_3_0_0_0_0_3](https://user-images.githubusercontent.com/742339/68154282-0fb14400-fefc-11e9-88ed-6ebe02bee6b9.png)

**Comment by jamesbowman** [comment]
Please can you provide more detail -- in particular why you think this is a bug OpenEXR Python?

**Comment by humayun** [comment]
Thank you. This was not bug in OpenEXR. That is more conversion from Float32 to uint8 and also gamma correction. I resolved that problem. 

Best
