### ISSUE TITLE
Outdated pypi repository

### ISSUE THREAD

**Issue by tiagoshibata** [jamesbowman/openexrpython#4]
Hi,

It seems that the [pypi repo](https://pypi.python.org/pypi/OpenEXR) is a bit outdated. Building fails in Python 3, would you mind updating it?

Thanks!

**Comment by so-rose** [comment]
I second this request. OpenEXR in Python 3 would be a lifesaver.

**Comment by adynathos** [comment]
> OpenEXR in Python 3 would be a lifesaver.

Of course having an updated PyPI package would be nice, but if you need to use it, it works when built from source.

**Comment by jamesbowman** [comment]
PyPI package updated to 1.3, which builds/regresses under 2.6, 2.7, 3.2 and 3.5:

https://pypi.python.org/pypi/OpenEXR/1.3.0

Closing.

**Comment by Amir-Arsalan** [comment]
@jamesbowman I did `pip3 install openexr` but I get some weird errors. Am I supposed to do something else before running the `pip` command?

**Comment by jamesbowman** [comment]
Yes, that should work. In fact I just did it and it succeeded.
What platform are you on? What are the specific errors?

```
~ $ sudo pip3 install openexr
Downloading/unpacking openexr
  Downloading OpenEXR-1.3.0.tar.gz
...
    
Successfully installed openexr
Cleaning up...
```

**Comment by Amir-Arsalan** [comment]
@jamesbowman Here's shows what I get after `pip3 install openexr`:

![1](https://user-images.githubusercontent.com/6061721/37728505-ce315308-2d10-11e8-8412-e9d786373c13.png)

**Comment by Amir-Arsalan** [comment]
@jamesbowman It seems that some other people have the same issues [[1]](https://stackoverflow.com/questions/45588103/install-openexr-for-python-with-pip-on-windows), [[2]](https://stackoverflow.com/questions/45601949/install-openexr-in-python-doesnt-work)

Did you try `pip3 install openexr` in Ubuntu or Windows? I am using Ubuntu

**Comment by tiagoshibata** [comment]
You are missing OpenEXR's headers. Install them and OpenEXR's libraries and the Python wrapper will compile.

**Comment by Amir-Arsalan** [comment]
@so-rose @tiagoshibata  Sorry maybe I should have mentioned that I did `sudo apt-get install libopenexr-dev` before doing `pip3 install openexr` but things still do not work. Could it be because libopenexr-dev works with Python 2?

**Comment by Amir-Arsalan** [comment]
I did a fresh Ubuntu install and things are fine now. I also had to do `sudo pip install openexr` to make things work.

**Comment by Amir-Arsalan** [comment]
@jamesbowman The OpenEXR repo has had [new commits](https://github.com/openexr/openexr/commits/master) in the past few months. I wonder, are you planning to update the pypi package in a soon future?

**Comment by jamesbowman** [comment]
Version 1.3.1 uploaded to PyPI. Closing.
