### ISSUE TITLE
Build failure on Windows with Python 3.10

### ISSUE THREAD

**Issue by pkgw** [jamesbowman/openexrpython#47]
It looks like this package won't build on Windows with Python 3.10 due to the lack of definition of a `ssize_t` symbol — see https://github.com/conda-forge/openexr-python-feedstock/pull/4 . My guess is that in 3.10 `Python.h` stops including some system header that was needed.

Based on my read of the code, I think it should fix things to replace the two instances of `ssize_t` with `Py_ssize_t` in `OpenEXR.cpp`.

**Comment by jamesbowman** [comment]
This code is no longer maintained -- see https://github.com/sanguinariojoe/pip-openexr
