### ISSUE TITLE
Linker Script python.map not found

### ISSUE THREAD

**Issue by MiriamJo** [jamesbowman/openexrpython#48]
I used the migrated python3 version of this code from [this repository](https://github.com/sanguinariojoe/pip-openexr). 

I cloned the repo to my pc and tried installing it with "python3.5m setup.py install". However, I keep getting this error:

`gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/OpenEXR -I/usr/local/include/OpenEXR -I/opt/local/include/OpenEXR -I/usr/include/Imath -I/usr/local/include/Imath -I/opt/local/include/Imath -I/opt/blender-2.79a/2.79/python/include/python3.5m -c OpenEXR.cpp -o build/temp.linux-x86_64-3.5/OpenEXR.o -g -std=c++11 -DVERSION="1.3.7"'`

`cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ g++ -pthread -shared -L/opt/lib/bz2/lib -L/opt/lib/lzma/lib -L/opt/lib/ssl/lib -L/opt/lib/zlib/lib -L/opt/lib/libc6/lib -L/opt/lib/ncurses/lib -L/opt/lib/gpm/lib -L/opt/lib/sqlite/lib -L/opt/lib/readline/lib -Wl,--version-script=python.map build/temp.linux-x86_64-3.5/OpenEXR.o -L/usr/lib -L/usr/local/lib -L/opt/local/lib -lIex -lHalf -lImath -lIlmImf -lz -o build/lib.linux-x86_64-3.5/OpenEXR.cpython-35m-x86_64-linux-gnu.so`

`/usr/bin/ld: cannot open linker script file python.map: File or Directory not found collect2: error: ld returned 1 exit status error: command 'g++' failed with exit status 1`

I'm really not sure what causes it. I tried changing the g++ and gcc version, added the c++11 flag, tried it with another openexr version int he first place. I really can't find the error.

I searched for the missing python.map file in my directories, but couldn't find it. Where do i get it from and how do i link it properly?
I installed all other libraries and prerequisites according to the openexr tutorial properly.

Kind regards.

**Comment by monajalal** [comment]
@MiriamJo any chance you may remember how to resolve this error?

**Comment by jamesbowman** [comment]
This code is no longer maintained -- see https://github.com/sanguinariojoe/pip-openexr
