### ISSUE TITLE
failed to Building wheel. macos14 python 3.11

### ISSUE THREAD

**Issue by Junhao90** [jamesbowman/openexrpython#52]
Processing ./openexrpython
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: OpenEXR
  Building wheel for OpenEXR (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for OpenEXR (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      <string>:18: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      <string>:19: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      OpenEXR.cpp:36:10: fatal error: 'ImathBox.h' file not found
      #include <ImathBox.h>
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for OpenEXR
Failed to build OpenEXR
ERROR: Could not build wheels for OpenEXR, which is required to install pyproject.toml-based projects

**Comment by jamesbowman** [comment]
This code is no longer maintained -- see https://github.com/sanguinariojoe/pip-openexr
